# Generated by Django 4.2.1 on 2023-05-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('unit', models.CharField(default='个', max_length=10, verbose_name='单位')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
    ]
