# Generated by Django 4.2.1 on 2023-05-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.warehouse', verbose_name='归属'),
        ),
    ]
