# Generated by Django 4.2.1 on 2023-05-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_alter_warehouse_options_alter_warehouse_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('max_row', models.CharField(max_length=20, verbose_name='行')),
                ('max_column', models.CharField(max_length=20, verbose_name='列')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '储位',
                'verbose_name_plural': '储位',
                'unique_together': {('warehouse', 'name')},
            },
        ),
    ]
