# Generated by Django 4.2.1 on 2023-05-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_alter_box_max_column_alter_box_max_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('max_row', models.PositiveSmallIntegerField(verbose_name='层数')),
                ('max_column', models.PositiveSmallIntegerField(verbose_name='每层储位数')),
            ],
            options={
                'verbose_name': '货架',
                'verbose_name_plural': '货架',
            },
        ),
        migrations.CreateModel(
            name='storage_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '库区',
                'verbose_name_plural': '库区',
            },
        ),
        migrations.CreateModel(
            name='storage_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(verbose_name='行')),
                ('column', models.PositiveSmallIntegerField(verbose_name='列')),
                ('item', models.CharField(max_length=20, verbose_name='物品')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.shelf', verbose_name='货架')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='parent',
        ),
        migrations.DeleteModel(
            name='box',
        ),
        migrations.AddField(
            model_name='storage_area',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.warehouse', verbose_name='所属仓库'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='storage_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.storage_area', verbose_name='库区'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('storage_area', 'name')},
        ),
    ]
