# Generated by Django 4.2.1 on 2023-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_shelf_storage_area_storage_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage_location',
            options={'verbose_name': '储位', 'verbose_name_plural': '储位'},
        ),
        migrations.AlterField(
            model_name='storage_area',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterUniqueTogether(
            name='storage_area',
            unique_together={('warehouse', 'name')},
        ),
    ]
