# Generated by Django 4.2.1 on 2023-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_alter_storage_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='max_column',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='每层储位数'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='max_row',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='层数'),
        ),
    ]
