# Generated by Django 4.2.1 on 2023-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_alter_shelf_max_column_alter_shelf_max_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveSmallIntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('item_list', models.JSONField(blank=True, default=list, verbose_name='清单')),
            ],
        ),
    ]
