# Generated by Django 4.2.1 on 2023-05-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商'},
        ),
    ]
