# Generated by Django 4.2.1 on 2023-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
